### ISSUE TITLE
Call for Code Release

### ISSUE THREAD

**Issue by AnonymXXXXX** [4AI/BeLLM#1]
First of all, congratulations on your paper being accepted to NAACL 2024.

A few months ago, I read the preprint you uploaded to ArXiv, where your model, based on LLaMA2, achieved a Spearman correlation coefficient score of 86.01 across seven STS benchmark tasks.

Recently, I noticed that you've updated your paper and that the corresponding experimental results have improved from 86.01 to 86.26.

We have been unable to replicate these results and are therefore eager to access the corresponding code. As per the ReadMe file, it was mentioned that the code would be made available by the end of March 2024. Given that it's now April 5,2024, and the code has not yet been released, could you please share the code or provide an update on its availability?

Thank you for your attention to this matter. We are keen to explore and build upon your work.

**Comment by SeanLee97** [comment]
@AnonymXXXXX Thank you for following our work and sorry for the delay. It should be released last week. But I was busy with the ACL rebuttal. Thus the schedule changed. 
I will return to work on it next week. Will let you know when push the code and pretrained weights.

**Comment by AnonymXXXXX** [comment]
Thanks for your reply!

**Comment by SeanLee97** [comment]
hi, I have pushed the code. More details are incoming

**Comment by AnonymXXXXX** [comment]
Thank you very much for open source your code, we will study it carefully.
